/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAEmpresaRouteImport } from './routes/_public.a-empresa'
import { Route as PublicContatoRouteImport } from './routes/_public.contato'
import { Route as PublicProdutosRouteImport } from './routes/_public.produtos'
import { Route as PublicProjetosRouteImport } from './routes/_public.projetos'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as PublicBlogIdRouteImport } from './routes/_public.blog.$id'
import { Route as PublicProdutoIdRouteImport } from './routes/_public.produto.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAEmpresaRoute = PublicAEmpresaRouteImport.update({
  id: '/a-empresa',
  path: '/a-empresa',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContatoRoute = PublicContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProdutosRoute = PublicProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjetosRoute = PublicProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIdRoute = PublicBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProdutoIdRoute = PublicProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRoute
  '/a-empresa': typeof PublicAEmpresaRoute
  '/contato': typeof PublicContatoRoute
  '/produtos': typeof PublicProdutosRoute
  '/projetos': typeof PublicProjetosRoute
  '/blog/$id': typeof PublicBlogIdRoute
  '/produto/$id': typeof PublicProdutoIdRoute
  '/blog/': typeof PublicBlogIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/a-empresa': typeof PublicAEmpresaRoute
  '/contato': typeof PublicContatoRoute
  '/produtos': typeof PublicProdutosRoute
  '/projetos': typeof PublicProjetosRoute
  '/': typeof PublicIndexRoute
  '/blog/$id': typeof PublicBlogIdRoute
  '/produto/$id': typeof PublicProdutoIdRoute
  '/blog': typeof PublicBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRoute
  '/_public/a-empresa': typeof PublicAEmpresaRoute
  '/_public/contato': typeof PublicContatoRoute
  '/_public/produtos': typeof PublicProdutosRoute
  '/_public/projetos': typeof PublicProjetosRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/blog/$id': typeof PublicBlogIdRoute
  '/_public/produto/$id': typeof PublicProdutoIdRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/a-empresa'
    | '/contato'
    | '/produtos'
    | '/projetos'
    | '/blog/$id'
    | '/produto/$id'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/a-empresa'
    | '/contato'
    | '/produtos'
    | '/projetos'
    | '/'
    | '/blog/$id'
    | '/produto/$id'
    | '/blog'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/a-empresa'
    | '/_public/contato'
    | '/_public/produtos'
    | '/_public/projetos'
    | '/_public/'
    | '/_public/blog/$id'
    | '/_public/produto/$id'
    | '/_public/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/a-empresa': {
      id: '/_public/a-empresa'
      path: '/a-empresa'
      fullPath: '/a-empresa'
      preLoaderRoute: typeof PublicAEmpresaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contato': {
      id: '/_public/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof PublicContatoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/produtos': {
      id: '/_public/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof PublicProdutosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projetos': {
      id: '/_public/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof PublicProjetosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$id': {
      id: '/_public/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof PublicBlogIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/produto/$id': {
      id: '/_public/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof PublicProdutoIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAEmpresaRoute: typeof PublicAEmpresaRoute
  PublicContatoRoute: typeof PublicContatoRoute
  PublicProdutosRoute: typeof PublicProdutosRoute
  PublicProjetosRoute: typeof PublicProjetosRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogIdRoute: typeof PublicBlogIdRoute
  PublicProdutoIdRoute: typeof PublicProdutoIdRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAEmpresaRoute: PublicAEmpresaRoute,
  PublicContatoRoute: PublicContatoRoute,
  PublicProdutosRoute: PublicProdutosRoute,
  PublicProjetosRoute: PublicProjetosRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogIdRoute: PublicBlogIdRoute,
  PublicProdutoIdRoute: PublicProdutoIdRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
